version: '3'

services:
  db:
    image: postgres:13
    container_name: challenge-one-db
    restart: on-failure
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}
    expose:
     - 5432

  backend:
    image: challenge-one-backend
    container_name: challenge-one-backend
    build:
      context: ./backend/
    restart: on-failure
    depends_on:
     - db
    ports:
     - 8000:8000
    env_file:
     - ./backend/.env
      
  frontend:
    image: challenge-one-frontend
    container_name: challenge-one-frontend
    build:
      context: ./frontend/
    restart: on-failure
    depends_on:
     - backend
    ports:
     - 80:80
